prosoft-edv/components

projects/components/table/src/table.component.spec.ts
projects/components/table/src/table.component.ts
projects/prosoft-components-demo/src/app/table-demo/table-demo.component.html
projects/prosoft-components-demo/src/app/table-demo/table-demo.component.ts

feat(table): Added a debounce to pagination

---

projects/components/form-field/src/form-field.component.ts
projects/prosoft-components-demo/src/app/form-field-demo/form-field-demo.component.ts

feat(form-field): recognize the [appearence] property of mat-form-field

---

projects/components/table/src/data/table-data-source.ts
projects/components/table/src/subcomponents/table-pagination.component.spec.ts
projects/components/table/src/subcomponents/table-pagination.component.ts
projects/components/table/src/table.component.html
projects/components/table/src/table.component.scss
projects/components/table/src/table.component.spec.ts
projects/components/table/src/table.component.ts
projects/components/table/src/table.module.ts

Adding "GoToPage" functionality

---

projects/components/table/src/subcomponents/table-header.component.ts

fix(table): fixed layout of table-header items

---

projects/components/table/public_api.ts
projects/components/table/src/directives/table.directives.spec.ts
projects/components/table/src/directives/table.directives.ts
projects/components/table/src/table.component.spec.ts
projects/components/table/src/table.component.ts
projects/prosoft-components-demo/src/app/table-demo/table-demo.component.html
projects/prosoft-components-demo/src/app/table-demo/table-demo.component.ts

Exposed PsTableRowDetailDirective so the user can call its toggle-function from his custom toggle button.

feat(table): Implemented an option to use a custom row detail toggle

---

projects/components/table/src/subcomponents/table-data.component.html
projects/components/table/src/table.component.spec.ts

fix(table): refreshable input is now working again

---

projects/components/table/src/subcomponents/table-data.component.html
projects/components/table/src/subcomponents/table-data.component.ts
projects/components/table/src/subcomponents/table-pagination.component.ts
projects/components/table/src/table.component.html
projects/components/table/src/table.component.scss

fix(table): cardLayout and pagination styling

---

docs/form.md
projects/components/core/src/exception-message-extractor.service.ts
projects/components/form/public_api.ts
projects/components/form/src/form-action.service.ts
projects/components/form/src/form-data-source.ts
projects/components/form/src/form.component.html
projects/components/form/src/form.component.scss
projects/components/form/src/form.component.spec.ts
projects/components/form/src/form.component.ts
projects/components/form/src/models.ts
projects/components/savebar/public_api.ts
projects/components/savebar/src/models.ts
projects/components/savebar/src/savebar.component.ts
projects/prosoft-components-demo/src/app/form-demo/form-data-source-demo.component.ts
projects/prosoft-components-demo/src/app/form-demo/form-demo.component.ts
projects/prosoft-components-demo/src/app/form-demo/form-demo.module.ts
projects/prosoft-components-demo/src/app/form-demo/form-inputs-demo.component.ts

The ps-form behaviour can now be controlled with a dataSource. The other inputs and outputs are now
deprecated.

feat(form): added dataSource input

---

docs/table.md
projects/components/table/src/data/table-data-source.spec.ts
projects/components/table/src/data/table-data-source.ts

For example the route params observable can be set as loadTrigger$ to trigger the updateData method when the params change.
fix #73

feat(table): a loadTrigger can be provided to the data source

---

projects/components/form/public_api.ts
projects/components/form/src/form-data-source.ts
projects/components/form/src/form.component.html
projects/components/form/src/form.component.scss
projects/components/form/src/form.component.spec.ts
projects/components/form/src/form.component.ts
projects/components/utils/public_api.ts
projects/components/utils/src/dom.ts
projects/prosoft-components-demo/src/app/form-demo/form-data-source-demo.component.ts

fix(form): save errors should be more recognizable for the user

---

projects/components/select/src/defaults/default-select-data-source.spec.ts
projects/components/select/src/defaults/default-select-data-source.ts
projects/components/select/src/defaults/default-select-service.spec.ts
projects/components/select/src/models.ts

fix(select): add original item to PsSelectItem

---

.github/workflows/push-master.yml

Added a GH-Action wich deploys the latest push to master on Github-pages
fix #46

ci(push-master): created action for automatic GH-pages update

---

projects/components/form/src/form.component.html
projects/components/savebar/src/savebar.component.html
projects/components/table/src/subcomponents/table-pagination.component.ts
projects/components/table/src/table.component.scss
projects/components/table/src/table.component.spec.ts
projects/components/table/src/table.component.ts

fix: elevation and border radius adjustments

---

docs/number-input.md
projects/components/number-input/src/number-input.component.spec.ts
projects/components/number-input/src/number-input.component.ts
projects/prosoft-components-demo/src/app/number-input-demo/number-input-demo.component.ts

formatting with input formatInput was broken in case formatInput was false
BREAKING CHANGE: formatInput removed

fix(number-input): formatting permanently active in apps locale

---

docs/flip-container.md
projects/components/flip-container/src/flip-container.component.html
projects/components/flip-container/src/flip-container.component.spec.ts
projects/components/flip-container/src/flip-container.component.ts
projects/components/table/src/table.component.html
projects/components/table/src/table.component.spec.ts
projects/components/table/src/table.component.ts
projects/prosoft-components-demo/src/app/flip-container-demo/flip-container-demo.component.html

BREAKING CHANGE: show property is now named active
fix #107

feat(flip-container): added methods to flip to back/front

---

projects/components/table/src/table.component.spec.ts
projects/components/table/src/table.component.ts
projects/prosoft-components-demo/src/app/table-demo/table-demo.component.html

fix(table): view now updates when view/content children change

---

projects/components/CHANGELOG.md
projects/components/package.json

- @prosoft/components@0.1.0-alpha.21

chore(release): release

---

projects/components/form-field/src/form-field.component.spec.ts
projects/components/form-field/src/form-field.component.ts

fix(formfield): formField now adheres MAT_FORM_FIELD_DEFAULT_OPTIONS

---

docs/flip-container.md
projects/components/flip-container/src/flip-container.component.html
projects/components/flip-container/src/flip-container.component.scss
projects/components/flip-container/src/flip-container.component.ts
projects/components/table/src/table.component.html
projects/prosoft-components-demo/src/app/flip-container-demo/flip-container-demo.component.html
projects/prosoft-components-demo/src/app/flip-container-demo/flip-container-demo.component.ts
projects/prosoft-components-demo/src/app/flip-container-demo/flip-container-demo.module.ts

Adds animation option 'fade' to the flip-container. Changeable via input 'animation'. Changes
ps-table flip-container to animation 'fade'
BREAKING CHANGE: ps-table flip animation changed

feat(flip-container): add animation option 'fade'

---

projects/components/CHANGELOG.md
projects/components/package.json

- @prosoft/components@2.0.0-alpha.8

chore(release): 2.0.0-alpha.8

---

docs/view.md
projects/components/select/src/select.component.spec.ts
projects/components/view/index.ts
projects/components/view/package.json
projects/components/view/public_api.ts
projects/components/view/src/testing/view.harness.ts
projects/components/view/src/view-data-source.ts
projects/components/view/src/view.component.html
projects/components/view/src/view.component.scss
projects/components/view/src/view.component.spec.ts
projects/components/view/src/view.component.ts
projects/components/view/src/view.module.ts
projects/prosoft-components-demo/src/app/app.component.html
projects/prosoft-components-demo/src/app/app.module.ts
projects/prosoft-components-demo/src/app/view-demo/view-demo.component.ts
projects/prosoft-components-demo/src/app/view-demo/view-demo.module.ts

Wrapper that handles loading states and errors for readonly views

feat(view): added new PsViewComponent

---

projects/components/CHANGELOG.md
projects/components/package.json

- @prosoft/components@2.0.0-alpha.9

chore(release): 2.0.0-alpha.9

---

docs/form.md
docs/view.md
projects/components/dialog-wrapper/src/dialog-wrapper.component.ts
projects/components/form/src/form-data-source.ts
projects/components/form/src/form.component.ts
projects/components/view/public_api.ts
projects/components/view/src/view-data-source.ts
projects/components/view/src/view.component.ts
projects/prosoft-components-demo/src/app/form-demo/form-data-source-demo.component.ts
projects/prosoft-components-demo/src/app/view-demo/view-demo.component.ts

Added typing of exception getter in dialog-wrapper
Replaced IPsViewException with IPsException
Made properties of type IPsException nullable
Replaced deprecated types in form

fix(release): broken typings

---

projects/components/CHANGELOG.md
projects/components/package.json

- @prosoft/components@2.0.0-alpha.10

chore(release): 2.0.0-alpha.10

---

projects/components/CHANGELOG.md
projects/components/package.json

- @prosoft/components@2.0.0-alpha.11

chore(release): 2.0.0-alpha.11

---

projects/components/CHANGELOG.md
projects/components/package.json

- @prosoft/components@2.0.0-alpha.12

chore(release): 2.0.0-alpha.12

---

projects/components/number-input/src/number-input.component.spec.ts
projects/components/number-input/src/number-input.component.ts
projects/components/utils/public_api.ts
projects/components/utils/src/string.spec.ts
projects/components/utils/src/string.ts

fix(number-input): numbers getting truncated
