prosoft-edv/components

projects/components/form/src/form.component.spec.ts, projects/components/form/src/form.component.ts, projects/components/savebar/src/savebar.component.ts, projects/components/savebar/src/savebar.intl.ts
The savebar ViewChild wasn't resolved yet in this case, so the intl property evaluated to an empty
object
=> fix(form): when loading instantly failed, then cancel label wasn't shown

projects/components/form-field/src/form-field.component.spec.ts, projects/components/form-field/src/form-field.component.ts, projects/prosoft-components-demo/src/app/form-field-demo/form-field-demo.component.ts
The check for an existing checkbox label didn't account for labels set with an async pipe and also
deleted the text node where angular wanted to set the label text when it was resolved. Now the text
node will be updated instead of overwritten, so angular can revert the label if it is set with an
async pipe.
=> fix(form-field): async checkbox labels in the template are overwritten

projects/components/form/src/form.component.spec.ts, projects/components/form/src/form.component.ts, projects/components/savebar/src/savebar.component.html, projects/prosoft-components-demo/src/app/form-demo/form-demo.component.ts
when no form is provided, then several features wont work:
- error messages can't be shown
- limited automatic disabling of the save buttons
- save function, events and the service wont get a save value
- no automatic position sticky for the savebar
=> WIP feat(form): form input is now optional

projects/components/block-ui/src/block-ui.component.ts, projects/prosoft-components-demo/src/app/block-ui-demo/block-ui-demo.component.ts
Before the spinner was in the middle of the screen within the bounds of the blocked component. Now
it is in the middle of the component but tries to stay within the visible screen area.
=> fix(block-ui): spinner position is now in the middle in more cases

projects/components/slider/src/slider.component.scss
When hovering a handle the cursor now shows grab. When clicking and draging the cursor now shows
grabbing.
fix #35
=> style(slider): slider now shows "grab" and "grabbing" cursor

projects/components/table/src/subcomponents/table-sort.component.ts
The sort direction buttons were squased together an were squashed on the mat-select. Every element
is now sepereated by .2em from each other.
fix #36
=> style(table): seperated sort direction buttons

projects/components/select/src/select.component.ts
onContainerClick and setDescribedByIds calls were not passed down to mat-select
=> fix(select): form-field container click now opens select

projects/components/table/public_api.ts, projects/components/table/src/helper/state-manager.spec.ts, projects/components/table/src/helper/state-manager.ts, projects/components/table/src/table.component.ts
A state manager can now be provided to controll where the table state is stored. Default is
PsTableUrlStateManager but a PsTableMemoryStateManager now also comes with the table.
=> feat(table): current table state can be controlled with a state manager

projects/components/form-field/src/form-field.component.spec.ts, projects/components/form-field/src/form-field.component.ts, projects/components/form-field/src/form-field.module.ts, projects/prosoft-components-demo/src/app/form-field-demo/form-field-demo.component.ts
Hints aren't initially visible anymore, they now have to be toggled via a hint button. Hints and
errors are shown in a bubble that expands on hover/focus.
=> feat(form-field): hint/error are shown in an expandable bubble

projects/components/form-field/public_api.ts, projects/components/form-field/src/form-field.component.spec.ts, projects/components/form-field/src/form-field.component.ts, projects/prosoft-components-demo/src/app/form-field-demo/form-field-demo.component.ts
subscriptType resize resizes the form-field if the error or hint spans over multiple lines and is
now the default. hintToggle  controls if the hint toggle button should be used (default false)
BREAKING CHANGE: Hint toggle button is now off by default and form-field resizes for multiline
hint/error by default
=> feat(form-field): subscriptType and hintToggle inputs

projects/components/select/src/select-data.component.spec.ts, projects/components/select/src/select-data.component.ts
values set before AfterViewInit of ps-select-data didn't trigger selectedValuesChanged of the
datasource
=> fix(select): values set before AfterViewInit are now working correctly

angular.json, projects/components/table/src/data/table-data-source.spec.ts, projects/components/table/src/data/table-data-source.ts, projects/components/table/src/subcomponents/table-data.component.html, projects/prosoft-components-demo/src/app/slider-demo/slider-demo.component.ts, projects/prosoft-components-demo/src/app/table-demo/table-demo.component.ts
With mode 'client' the rendered rows won't be trashed and rerendered anymore if the data is already
cached and can be synchronously filtered/sorted/paged. Also a trackBy function can now be set in the
dataSource.
=> perf(table): less layout trashing on data update

docs/table.md, projects/components/table/src/services/table-settings.service.ts, projects/components/table/src/subcomponents/table-settings.component.spec.ts, projects/components/table/src/subcomponents/table-settings.component.ts, projects/components/table/src/table.component.spec.ts, projects/components/table/src/table.component.ts, projects/prosoft-components-demo/src/app/table-demo/table-demo.module.ts
The table now doesn't have to subscribe to settings and defaultPageSize separatelly
BREAKING CHANGE: The PsTableSettingsService now has a getStream method instead of the settings$ and defaultPageSize$ observables
=> refactor(table): table settings cleanup

docs/savebar.md, projects/components/core/src/intl.ts, projects/components/savebar/src/savebar.component.html, projects/components/savebar/src/savebar.component.spec.ts, projects/components/savebar/src/savebar.component.ts, projects/prosoft-components-demo/src/app/savebar-demo/savebar-demo.component.ts
This feature is unused and doesn't really fit to the scope of the savebar. This should be done with
psSavebarRightContent.
BREAKING CHANGE: removed prev/next button support
=> refactor(savebar): remove prev/next button support

projects/components/table/public_api.ts, projects/components/table/src/data/table-data-source.spec.ts, projects/components/table/src/data/table-data-source.ts, projects/components/table/src/models.ts, projects/components/table/src/table.component.spec.ts, projects/components/table/src/table.component.ts
Things to be aware of:
- loadTrigger$ emits before the ps-table called connect() are ignored
- the triggerData passed to loadFn can still be null if loadTrigger$ didn't emit.
- can't pass new trigger data to a manual updateData() call. Should this be allowed?
fixes #88
=> feat(table): pass loadTrigger data to loadFn

projects/components/form/src/form.component.scss, projects/components/table/src/table.component.scss, projects/components/table/src/table.component.spec.ts, projects/components/table/src/table.component.ts
table with card layout now has a background for the header. form css class selectivity increased to
prevent material styles from overriding the styles of the error card.
=> fix: style fixes for table and form

projects/components/table/src/subcomponents/table-header.component.ts
When the actions container was the only header item, then it got left aligned. This is now fixed.
fix #103
=> fix(table): actions always stay right aligned

projects/components/select/src/defaults/default-select-data-source.spec.ts, projects/components/select/src/defaults/default-select-data-source.ts, projects/components/select/src/defaults/default-select-service.spec.ts, projects/components/select/src/models.ts, projects/components/select/src/select-data.component.ts, projects/components/select/src/select.component.spec.ts, projects/prosoft-components-demo/src/app/select-demo/select-demo.component.ts
items can be disabled by providing a 'disabledKey' to the DataSourceOptions and setting the property
of that name to true
=> feat(select): items can be disabled

projects/components/table/src/data/table-data-source.spec.ts, projects/components/table/src/data/table-data-source.ts
The properties of IPsTableFilterResult were pascal case instead of camel case like the rest of the
code.
BREAKING CHANGE: IPsTableFilterResult properties are now camel case
fix #89
=> refactor(table): fixed casing of IPsTableFilterResult properties

projects/components/table/src/data/table-data-source.spec.ts, projects/components/table/src/data/table-data-source.ts, projects/prosoft-components-demo/src/app/slider-demo/slider-demo.module.ts
When a load data request was already in flight and updateData was called with forceReload false,
then the data loading was incorrectly cancelled
=> fix(table): don't cancel data loading when only the view is updated

projects/components/select/src/select-data.component.spec.ts, projects/components/select/src/select-data.component.ts
when using reactive forms and patching the form control with emitEvent false, then the ps-select component didn't propagate the value to the datasource. As a result the ps-select didn't show the selected value in the ui.
=> fix(select): propagate value when form is patched with emitEvent false

projects/components/select/src/select-data.component.spec.ts, projects/components/select/src/select-data.component.ts
`[dataSource]="'lookup'"` caused a lot of `PsSelectService.createDataSource` calls.
=> fix(select): don't recreate datasource when input doesn't change

projects/components/select/src/select.component.spec.ts, projects/components/select/src/select.component.ts
Mat-Label was not visible until first/click or sits tight on top since last ps-select update.
fix #139
=> fix(ps-select): re-applies stateChanges patch and fixes label

projects/components/form-field/src/form-field.component.ts, projects/components/select/src/select.component.ts, projects/prosoft-components-demo/src/app/app.module.ts, projects/prosoft-components-demo/src/app/form-field-demo/form-field-demo.component.html, projects/prosoft-components-demo/src/app/form-field-demo/form-field-demo.component.ts
The outline gap of a form field is now calculated correctly with a ps-select inside.
Default appearance of demo app changed to 'outline'
=> fix(select): outline gap calculated correctly with ps-select

docs/block-ui.md, projects/components/block-ui/src/block-ui.component.ts, projects/components/table/src/data/table-data-source.spec.ts, projects/components/table/src/data/table-data-source.ts, projects/components/table/src/table.component.html, projects/components/table/src/table.component.scss, projects/components/table/src/table.module.ts, projects/prosoft-components-demo/src/app/block-ui-demo/block-ui-demo.component.ts, projects/prosoft-components-demo/src/app/block-ui-demo/block-ui-demo.module.ts, projects/prosoft-components-demo/src/app/table-demo/table-demo.component.html, projects/prosoft-components-demo/src/app/table-demo/table-demo.component.ts
The current rows are only overlayed with a loading spinner while loading the new page.
This prevents a complete removal and rebuild of the rows.
=> perf(table): paginating keeps rows while loading

projects/components/utils/public_api.ts, projects/components/utils/src/auto-form-array.spec.ts, projects/components/utils/src/auto-form-array.ts
Add Benedikts form array extension auto-resizes on patchValue.
This includes some small changes to the original code to adhere to
our linter standards, here is the gist of it:
```
--- a/./projects/components/utils/src/auto-form-array.ts
+++ b/original_auto-form-array.ts
@@ -21,8 +21,8 @@ export class AutoFormArray extends FormArray {
super([], validatorOrOpts, asyncValidator);
}
-  public override patchValue(
-    value: unknown[],
+    public patchValue(
+        value: any[],
options?: {
onlySelf?: boolean;
emitEvent?: boolean;
@@ -32,8 +32,8 @@ export class AutoFormArray extends FormArray {
return super.patchValue(value, options);
}
-  public override reset(
-    value?: { length: number },
+    public reset(
+        value?: any,
options?: {
onlySelf?: boolean;
emitEvent?: boolean; …
```
=> feat: add auto-form-array
